// <auto-generated />
using BlazorCRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCRUD.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211223085440_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("BlazorCRUD.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is some example cpntent for post 1. The content is very interesting an I just wanted it to be two sentences long.",
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is some example cpntent for post 2. The content is very interesting an I just wanted it to be two sentences long.",
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is some example cpntent for post 3. The content is very interesting an I just wanted it to be two sentences long.",
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "This is some example cpntent for post 4. The content is very interesting an I just wanted it to be two sentences long.",
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "This is some example cpntent for post 5. The content is very interesting an I just wanted it to be two sentences long.",
                            Title = "Post 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "This is some example cpntent for post 6. The content is very interesting an I just wanted it to be two sentences long.",
                            Title = "Post 6"
                        },
                        new
                        {
                            Id = 7,
                            Content = "This is some example cpntent for post 7. The content is very interesting an I just wanted it to be two sentences long.",
                            Title = "Post 7"
                        },
                        new
                        {
                            Id = 8,
                            Content = "This is some example cpntent for post 8. The content is very interesting an I just wanted it to be two sentences long.",
                            Title = "Post 8"
                        },
                        new
                        {
                            Id = 9,
                            Content = "This is some example cpntent for post 9. The content is very interesting an I just wanted it to be two sentences long.",
                            Title = "Post 9"
                        },
                        new
                        {
                            Id = 10,
                            Content = "This is some example cpntent for post 10. The content is very interesting an I just wanted it to be two sentences long.",
                            Title = "Post 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
